//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationGUIMayTinh.DungQLMTVoiWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ePhongHoc", Namespace="http://schemas.datacontract.org/2004/07/EntitiesQLMayTinh")]
    [System.SerializableAttribute()]
    public partial class ePhongHoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsPhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TangLauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenPhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToaNhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsPhong {
            get {
                return this.MsPhongField;
            }
            set {
                if ((object.ReferenceEquals(this.MsPhongField, value) != true)) {
                    this.MsPhongField = value;
                    this.RaisePropertyChanged("MsPhong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TangLau {
            get {
                return this.TangLauField;
            }
            set {
                if ((this.TangLauField.Equals(value) != true)) {
                    this.TangLauField = value;
                    this.RaisePropertyChanged("TangLau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenPhong {
            get {
                return this.TenPhongField;
            }
            set {
                if ((object.ReferenceEquals(this.TenPhongField, value) != true)) {
                    this.TenPhongField = value;
                    this.RaisePropertyChanged("TenPhong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToaNha {
            get {
                return this.ToaNhaField;
            }
            set {
                if ((object.ReferenceEquals(this.ToaNhaField, value) != true)) {
                    this.ToaNhaField = value;
                    this.RaisePropertyChanged("ToaNha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eMayTinh", Namespace="http://schemas.datacontract.org/2004/07/EntitiesQLMayTinh")]
    [System.SerializableAttribute()]
    public partial class eMayTinh : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HardDiskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaMayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsPhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VGAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPU {
            get {
                return this.CPUField;
            }
            set {
                if ((object.ReferenceEquals(this.CPUField, value) != true)) {
                    this.CPUField = value;
                    this.RaisePropertyChanged("CPU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HardDisk {
            get {
                return this.HardDiskField;
            }
            set {
                if ((object.ReferenceEquals(this.HardDiskField, value) != true)) {
                    this.HardDiskField = value;
                    this.RaisePropertyChanged("HardDisk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaMay {
            get {
                return this.MaMayField;
            }
            set {
                if ((object.ReferenceEquals(this.MaMayField, value) != true)) {
                    this.MaMayField = value;
                    this.RaisePropertyChanged("MaMay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Monitor {
            get {
                return this.MonitorField;
            }
            set {
                if ((object.ReferenceEquals(this.MonitorField, value) != true)) {
                    this.MonitorField = value;
                    this.RaisePropertyChanged("Monitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsPhong {
            get {
                return this.MsPhongField;
            }
            set {
                if ((object.ReferenceEquals(this.MsPhongField, value) != true)) {
                    this.MsPhongField = value;
                    this.RaisePropertyChanged("MsPhong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAM {
            get {
                return this.RAMField;
            }
            set {
                if ((object.ReferenceEquals(this.RAMField, value) != true)) {
                    this.RAMField = value;
                    this.RaisePropertyChanged("RAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VGA {
            get {
                return this.VGAField;
            }
            set {
                if ((object.ReferenceEquals(this.VGAField, value) != true)) {
                    this.VGAField = value;
                    this.RaisePropertyChanged("VGA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DungQLMTVoiWCF.IQuanLyMayTinh")]
    public interface IQuanLyMayTinh {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyMayTinh/getAllPhongHoc", ReplyAction="http://tempuri.org/IQuanLyMayTinh/getAllPhongHocResponse")]
        PresentationGUIMayTinh.DungQLMTVoiWCF.ePhongHoc[] getAllPhongHoc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyMayTinh/getAllPhongHoc", ReplyAction="http://tempuri.org/IQuanLyMayTinh/getAllPhongHocResponse")]
        System.Threading.Tasks.Task<PresentationGUIMayTinh.DungQLMTVoiWCF.ePhongHoc[]> getAllPhongHocAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyMayTinh/getMayTinhThuocPhong", ReplyAction="http://tempuri.org/IQuanLyMayTinh/getMayTinhThuocPhongResponse")]
        PresentationGUIMayTinh.DungQLMTVoiWCF.eMayTinh[] getMayTinhThuocPhong(string maphonghoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyMayTinh/getMayTinhThuocPhong", ReplyAction="http://tempuri.org/IQuanLyMayTinh/getMayTinhThuocPhongResponse")]
        System.Threading.Tasks.Task<PresentationGUIMayTinh.DungQLMTVoiWCF.eMayTinh[]> getMayTinhThuocPhongAsync(string maphonghoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyMayTinh/CheckIfExist", ReplyAction="http://tempuri.org/IQuanLyMayTinh/CheckIfExistResponse")]
        bool CheckIfExist(string maMay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyMayTinh/CheckIfExist", ReplyAction="http://tempuri.org/IQuanLyMayTinh/CheckIfExistResponse")]
        System.Threading.Tasks.Task<bool> CheckIfExistAsync(string maMay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyMayTinh/insertMayTinh", ReplyAction="http://tempuri.org/IQuanLyMayTinh/insertMayTinhResponse")]
        int insertMayTinh(PresentationGUIMayTinh.DungQLMTVoiWCF.eMayTinh mtmoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyMayTinh/insertMayTinh", ReplyAction="http://tempuri.org/IQuanLyMayTinh/insertMayTinhResponse")]
        System.Threading.Tasks.Task<int> insertMayTinhAsync(PresentationGUIMayTinh.DungQLMTVoiWCF.eMayTinh mtmoi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuanLyMayTinhChannel : PresentationGUIMayTinh.DungQLMTVoiWCF.IQuanLyMayTinh, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuanLyMayTinhClient : System.ServiceModel.ClientBase<PresentationGUIMayTinh.DungQLMTVoiWCF.IQuanLyMayTinh>, PresentationGUIMayTinh.DungQLMTVoiWCF.IQuanLyMayTinh {
        
        public QuanLyMayTinhClient() {
        }
        
        public QuanLyMayTinhClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuanLyMayTinhClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuanLyMayTinhClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuanLyMayTinhClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PresentationGUIMayTinh.DungQLMTVoiWCF.ePhongHoc[] getAllPhongHoc() {
            return base.Channel.getAllPhongHoc();
        }
        
        public System.Threading.Tasks.Task<PresentationGUIMayTinh.DungQLMTVoiWCF.ePhongHoc[]> getAllPhongHocAsync() {
            return base.Channel.getAllPhongHocAsync();
        }
        
        public PresentationGUIMayTinh.DungQLMTVoiWCF.eMayTinh[] getMayTinhThuocPhong(string maphonghoc) {
            return base.Channel.getMayTinhThuocPhong(maphonghoc);
        }
        
        public System.Threading.Tasks.Task<PresentationGUIMayTinh.DungQLMTVoiWCF.eMayTinh[]> getMayTinhThuocPhongAsync(string maphonghoc) {
            return base.Channel.getMayTinhThuocPhongAsync(maphonghoc);
        }
        
        public bool CheckIfExist(string maMay) {
            return base.Channel.CheckIfExist(maMay);
        }
        
        public System.Threading.Tasks.Task<bool> CheckIfExistAsync(string maMay) {
            return base.Channel.CheckIfExistAsync(maMay);
        }
        
        public int insertMayTinh(PresentationGUIMayTinh.DungQLMTVoiWCF.eMayTinh mtmoi) {
            return base.Channel.insertMayTinh(mtmoi);
        }
        
        public System.Threading.Tasks.Task<int> insertMayTinhAsync(PresentationGUIMayTinh.DungQLMTVoiWCF.eMayTinh mtmoi) {
            return base.Channel.insertMayTinhAsync(mtmoi);
        }
    }
}
